FROM node:18-alpine

WORKDIR /home/node/app
COPY package.json ./
RUN npm install -g npm-check-updates
RUN ncu -u
RUN npm install
COPY . .
ENV NODE_PATH=./build
RUN npm run build
EXPOSE 3000
CMD npm run dev